name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Setup ASP .NET
      uses: nuget/setup-nuget@v1
      with:
        nuget-version: ${{env.NUGET_VERSION}}
        
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
      
    - name: Cache SonarCloud packages
      uses: actions/cache@v1
      with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar  
    
    - name: Cache SonarCloud scanner
      id: cache-sonar-scanner
      uses: actions/cache@v1
      with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner
    
    - name: Install SonarCloud scanner
      if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
      shell: powershell
      run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner
          
    - name: Restore dependencies
      run: dotnet restore project1/TTGWebUI # The filepath will differ for yours
      
    - name: Test
      run: dotnet test project1/TTGWebUI --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
      
    - name: Build and analyze
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      shell: powershell
      run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"211004-Reston-NET_Colin-Mudie-P1" /o:"211004-reston-net" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.exclusions="**WebUI/wwwroot/lib/**" /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.vs.vstest.reportsPaths="**/TestResult/*trx"
          dotnet build project1/TTGWebUI  --configuration Release
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}" 
    
    
  deploy:
    needs: build
    runs-on: ubuntu-latest # Using ubuntu this time
    environment:
      name: 'Production' # Let's us setup an environment named publish and you can see it in my repository
      
    steps:
    #Sets our SDK again
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Publish
      run: dotnet publish project1/TTGWebUI --configuration Release -o ./publish
      
    - name: Upload sonarscanner report
      uses: actions/upload-artifact@v2
      with:
        name: TTGWebUI
        path: ./project1/TTGWebUI/publish
    
    - name: Deploy
      uses: azure/webapps-deploy@v2
      with:
        app-name: Table-Top-Games # Replace this with your web app name
        publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH}}
        package: ./project1/TTGWebUI/publish
